export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_FRIENDS = 'ADD_FRIENDS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_NEW_MESSAGES = 'SET_NEW_MESSAGES';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';

export const SET_SIDEBAR_STATUS = 'SET_SIDEBAR_STATUS';




export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';